### ISSUE TITLE
How does Turbonomic report back management to update the turbo cluster?

### ISSUE THREAD

**Issue by jahruhn** [cloud-pak-gitops/turbo-gitops#16]
How does Turbonomic report back to management to update the turbo cluster?

**Comment by gyliu513** [comment]
@jahruhn you can update https://github.com/IBM/turbo-gitops/blob/main/kubeturbo/values.yaml and commit the changes, argocd will get all of the changes and apply to the cluster.

For customers who want to use gitops, the best practise is they can create their own repo using this template, and use their own repo to install turbo, update turbo etc. Once there are code commit, gitops will be triggered either manually or automatically.

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/4461983/173446813-5e89ef15-6154-47e7-8e4c-1a6851994565.png">

**Comment by jahruhn** [comment]
Is this the feedback loop from Turbonomic to GitOps? Or is the customer required to run this himself on GitOps? The first would be preferable.

**Comment by gyliu513** [comment]
@jahruhn for any gitops operations, the best practise is clients can get all of the source code for gitops and maintain by themselves, as they may want to do some customize configuration for their cluster by creating some PRs. Does this make sense?

**Comment by jahruhn** [comment]
Thank you for clearing this up. I am actually looking for a solution where Turbonomic rewrites the configurations file to automatically adjust the resources of the vm's to be smaller or bigger depending on the application needs. Would this be a good use case for Gitops with Turbonomic?

**Comment by gyliu513** [comment]
@jahruhn it is some other features should be covered by Turbo, which is out of scope of this project, let us get some help from Turbo team :)
